### PR TITLE
Add script to replace chromosome names in tabular files

### PR DESCRIPTION
**Pull request by nsoranzo**
using mapping files from this repo.

### CODE REVIEW

**Comment by dpryan79** [comment]
I've had a couple requests from people that this repo be kept strictly conversion tables without additional scripts. Can you post that as a gist or something though? It'd be good to at least link to a few of these (I have a couple that I should post myself) so people needn't reinvent the wheel.

**Comment by nsoranzo** [comment]
I'm going to write a Galaxy wrapper for this script, so I may well include it alongside the XML file. I'd like to leave this open until I have a URL for it.

**Comment by dpryan79** [comment]
Sounds good!

**Comment by nsoranzo** [comment]
A slightly different version of this Python script is available at https://github.com/TGAC/earlham-galaxytools/blob/master/tools/replace_chromosome_names/replace_chromosome_names.py

Its Galaxy wrapper is available on the main ToolShed at https://toolshed.g2.bx.psu.edu/view/earlhaminst/replace_chromosome_names

**Pull request closed without merging**
